name: Build

on:
  push:
    branches:
      - main  # Adjust this to match your main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Use Windows virtual environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'  # Adjust to your preferred .NET version

    - name: Restore dependencies
      run: dotnet restore
      working-directory: Calender

    - name: Build
      run: dotnet build --configuration Release
      working-directory: Calender

  download:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Publish
      run: dotnet publish --configuration Release --output E:\
      working-directory: Calender

    - name: Copy artifacts
      run: |
        robocopy Calender\bin\Release E:\ /E
