name: Build

on:
  push:
    branches:
      - main  # Adjust this to match your main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Use Windows virtual environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'  # Adjust to your preferred .NET version

    - name: Restore dependencies
      run: dotnet restore
      working-directory: Calender

    - name: Build
      run: dotnet build --configuration Release
      working-directory: Calender

  download:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download artifacts
      uses: actions/github-script@v5
      with:
        script: |
          $response = Invoke-RestMethod -Uri "https://api.github.com/repos/your-username/your-repo/actions/runs/${{ github.event.workflow_run.id }}/artifacts"

          $artifacts = $response.artifacts | Where-Object { $_.name -eq 'Release' }
          if ($artifacts.Count -gt 0) {
            $artifact = $artifacts[0]
            $downloadUrl = $artifact.archive_download_url
            $downloadPath = './downloaded_artifacts'
            Invoke-WebRequest -Uri $downloadUrl -OutFile "$downloadPath/Release.zip"
            Write-Output 'Artifacts downloaded successfully.'
          } else {
            Write-Output 'No artifacts found to download.'
          }
