name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: D:\calender_api\Calender\Calendar.sln

    - name: Build
      run: dotnet build --configuration Release
      working-directory: D:\calender_api\Calender\Calendar.sln
   
